
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt1st = new javax.swing.JTextField();
        txt2nd = new javax.swing.JTextField();
        txt3rd = new javax.swing.JTextField();
        txt4th = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Verify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        jLabel1.setText("1ST QUARTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel2.setText("2ND QUARTER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel3.setText("3RD QUARTER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel4.setText("4TH QUARTER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        getContentPane().add(txt1st, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, -1));

        txt2nd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ndActionPerformed(evt);
            }
        });
        getContentPane().add(txt2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 90, -1));

        txt3rd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3rdActionPerformed(evt);
            }
        });
        getContentPane().add(txt3rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 90, -1));
        getContentPane().add(txt4th, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 90, -1));

        jButton2.setText("AVERAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int age = Integer.parseInt(txt1.getText());
        if(age<18 && age<=100)
            JOptionPane.showConfirmDialog(null,"able to vote","welcome",JOptionPane.INFORMATION_MESSAGE);
        
        else if (age >=17 && age >=5)
            JOptionPane.showConfirmDialog(null,"unble to vote","welcome",JOptionPane.INFORMATION_MESSAGE);

       
        else
            JOptionPane.showConfirmDialog(null,"invalid to vote","welcome",JOptionPane.INFORMATION_MESSAGE);
}

      private void txt1stActionPerformed(java.awt.event.ActionEvent evt) {
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt2ndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ndActionPerformed

    private void txt3rdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3rdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3rdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int first = Integer.parseInt(txt1st.getText());
        int second = Integer.parseInt(txt2nd.getText());
        int third = Integer.parseInt(txt3rd.getText());
        int fourth = Integer.parseInt(txt4th.getText());
        
        float total = first + second + third + fourth;
        float total_average = total /4;
        JOptionPane.showConfirmDialog(null,"Final Average" + total_average,"Final Average", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt1st;
    private javax.swing.JTextField txt2nd;
    private javax.swing.JTextField txt3rd;
    private javax.swing.JTextField txt4th;
    // End of variables declaration//GEN-END:variables
}
